aitax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nts/', include('nts.urls')),
]

nts/urls.py
from django.urls import path
from .views import (
    nts_home,
    getcert,
    del_ctacert,
    get_idpw,
    set_ctaid,
    set_bsid,
    get_ctaidpw,
    get_bsidpw,
    nts_Z1001
)

app_name = 'nts'
urlpatterns = [
    path('', nts_home, name='ntshome'),
    path('ctaid/', set_ctaid, name='set_ctaid'),
    path('bsid/', set_bsid, name='set_bsid'),
    path('ctapw/', get_ctaidpw, name='get_ctaidpw'),
    path('bspw/', get_bsidpw, name='get_bsidpw'),
    path('getcert/', getcert, name='getcert'),
    path('del/', del_ctacert, name='cert-delete'),
    path('idpw/', get_idpw, name='get_idpw'),
    path('nts_Z1001/', nts_Z1001, name='nts_Z1001'),
]

nts/models.py
from django.db import models
from django.urls import reverse


class CtaCert(models.Model):

    cert_nm = models.CharField(max_length=100, verbose_name='인증서명')
    pub_dt = models.DateField(verbose_name='유효기간시작일')
    end_dt = models.DateField(verbose_name='유효기간종료일')
    org_nm = models.CharField(max_length=20, verbose_name='인증기관')
    oid = models.CharField(max_length=30, verbose_name='인증기관ID')
    sn = models.CharField(max_length=20, verbose_name='시리얼넘버')
    file1 = models.CharField(max_length=1000, verbose_name='인증서')
    file2 = models.CharField(max_length=1000, verbose_name='개인키')
    cert_pw = models.CharField(max_length=20, verbose_name='인증서비번')
    num_used = models.IntegerField(default=0, verbose_name='선택횟수', null=True, blank=True)

    def __str__(self):
        return self.cert_nm

    def get_absolute_url(self):
        return reverse("nts:ctacert-detail", kwargs={"pk": self.pk})

    class Meta:
        unique_together = (('cert_nm', 'end_dt'),)

class CtaIdPw(models.Model):
    # id = models.AutoField(primary_key=True)
    # id = models.PositiveIntegerField(auto_created=True, unique=True)
    ctacert = models.ForeignKey(CtaCert, on_delete=models.CASCADE)
    ctaid = models.CharField(max_length=6, verbose_name='세무대리인 ID', primary_key=True)
    # ctaid = models.CharField(max_length=6, verbose_name='세무대리인 ID')
    pw = models.CharField(max_length=20, verbose_name='세무대리인 PW')
    num_used = models.IntegerField(default=0, verbose_name='선택횟수', null=True, blank=True)

    def __str__(self):
        return self.ctaid
    
    def get_absolute_url(self):
        return reverse("nts:ctaidpw_detail", kwargs={"pk": self.pk})

    class Meta:
        unique_together = (('ctacert', 'ctaid'),)
class BsIdPw(models.Model):
    # id = models.AutoField(primary_key=True)
    ctacert = models.ForeignKey(CtaCert, on_delete=models.CASCADE)
    ctaidpw = models.ForeignKey(CtaIdPw, on_delete=models.CASCADE)
    bsid = models.CharField(max_length=20, verbose_name='사용자 ID', primary_key=True)
    pw = models.CharField(max_length=20, verbose_name='사용자 PW')
    num_used = models.IntegerField( default=0, verbose_name='선택횟수', null=True, blank=True)

    def __str__(self):
        return self.bsid

    def get_absolute_url(self):
        return reverse("nts:bsidpw_detail", kwargs={"pk": self.pk})

    class Meta:
        unique_together = (('ctacert', 'ctaidpw', 'bsid'),)
    
    

nts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db import IntegrityError 
from django.contrib import messages  # 경고창 https://hoy.kr/kxuTa
from django.http import JsonResponse
from django.core import serializers
from django.views.generic import View

import os, sys
# 상위폴더 내 파일 import  https://brownbears.tistory.com/296
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))

from .models import CtaCert, CtaIdPw, BsIdPw
from scripts.utils import get_cert_info, ift_call2
import json

import win32com.client
import binascii  # excel Hexadecimal to file(binary)

iftCertdll = win32com.client.Dispatch("iftCoreEngine.iftGate")
iftServicedll = win32com.client.Dispatch("iftWinExAdapter.clsAdapter")


def nts_home(request):
    template_name = 'nts/nts_home.html'
    ctacert_obj = CtaCert.objects.all()
    ctaidpw_obj = CtaIdPw.objects.all()
    bsidpw_obj = BsIdPw.objects.all()
    context = {
        'ctacert_obj': ctacert_obj,
        'ctaidpw_obj': ctaidpw_obj,
        'bsidpw_obj': bsidpw_obj
        }
    return render(request, template_name, context)

def set_ctaid(request):
    id_cert = request.GET.get('id_cert')
    ctaidpws = CtaIdPw.objects.filter(ctacert_id=id_cert).order_by('ctaid')
    return render(request, 'nts/ctaid_list_options.html', {'ctaidpws': ctaidpws})

def set_bsid(request):
    id_cert = request.GET.get('id_cert')
    id_ctaid = request.GET.get('id_ctaid')
    bsidpws = BsIdPw.objects.filter(ctacert_id=id_cert).filter(
        ctaidpw_id=id_ctaid).order_by('bsid')
    return render(request, 'nts/bsid_list_options.html', {'bsidpws': bsidpws})

def get_ctaidpw(request):
    id_ctaid = request.GET.get('id_ctaid')
    ctaidpw = CtaIdPw.objects.filter(ctaid__exact=id_ctaid)   
    # https://stackoverflow.com/questions/26373992/use-jsonresponse-to-serialize-a-queryset-in-django-1-7
    response = serializers.serialize('json', ctaidpw)
    return JsonResponse(response, safe=False)

def get_bsidpw(request):
    userId = request.GET.get('userId')
    bsidpw = BsIdPw.objects.filter(bsid__exact=userId)
    # https://stackoverflow.com/questions/26373992/use-jsonresponse-to-serialize-a-queryset-in-django-1-7
    response = serializers.serialize('json', bsidpw)
    return JsonResponse(response, safe=False)

def getcert(request):
    cert_info = get_cert_info()
    if cert_info == None:  # 취소 버튼 클릭시
        msg = "인증서를 선택해 주세요!!!"
        messages.add_message(request, messages.INFO, msg)
        return redirect("/nts/")
    new_cert = CtaCert(**cert_info)
    try:
        new_cert.save()
        msg = f"인증서 [{cert_info['cert_nm']}]가 저장되었습니다!!!"
        messages.add_message(request, messages.INFO, msg)
    except Exception as e:
        msg = f"[{cert_info['cert_nm']}] : 이미 입력된 인증서 입니다!!!"
        messages.add_message(request, messages.INFO, msg)
        return redirect("/nts/")
    return redirect("/nts/")

def del_ctacert(request):
    if request.method == "POST":
        id = request.POST['id']
        obj = get_object_or_404(CtaCert, id=id)
        res = obj.cert_nm
        context = {'object': res}
        obj.delete()
        return JsonResponse(context)
    return redirect("/nts/")


def get_idpw(request):
    
    if request.method == "POST":
        # ctaid = request.POST['agentId']
        
        res_cta_idpw = {
            'ctacert_id': request.POST['certId'],
            'ctaid': request.POST['agentId'],
            'pw': request.POST['agentPw'],
        }
        res_bs_idpw = {
            'ctacert_id': request.POST['certId'],
            'ctaidpw_id': request.POST['agentId'],
            'bsid': request.POST['userId'],
            'pw': request.POST['userPw'],
        }
        if (res_cta_idpw['ctacert_id'] != "" and
            res_cta_idpw['ctaid'] != "" and
            res_cta_idpw['pw'] != ""):
            new_cta_idpw = CtaIdPw(**res_cta_idpw)
            try:
                new_cta_idpw.save()
            except Exception as e:
                print("err : ", e)
                pass

        # ctaid 로 CtaIdPw 테이블 id 값 추출하여 res_bs_idpw 딕셔너리 업데이트
        
        # ctacert_id = CtaIdPw.objects.filter(ctaid__exact=ctaid).values()[0]['ctaid']
        # print(ctacert_id)
        # res_bs_idpw['ctaidpw_id'] = ctacert_id
        
        if (res_bs_idpw['ctacert_id'] != "" and
            res_bs_idpw['ctaidpw_id'] != "" and
            res_bs_idpw['bsid'] != "" and
                res_bs_idpw['pw'] != ""):

            new_bs_idpw = BsIdPw(**res_bs_idpw)
            try:
                new_bs_idpw.save()
            except Exception as e:
                print("err : ", e)
                pass

        response = {
            'res_cta_idpw': res_cta_idpw,
            'res_bs_idpw': res_bs_idpw
        }

    return JsonResponse(response)

# https://www.thewordcracker.com/miscellaneous/%ED%81%AC%EB%A1%AC%EC%97%90%EC%84%9C-err_connection_reset-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0/
# https://www.ionos.com/digitalguide/hosting/technical-matters/err-connection-refused/
def nts_Z1001(request):
    if request.method == 'POST':
        print(request.POST)
        req_dict = dict()
        req_dict['appCd'] = 'aitax'
        req_dict['orgCd'] = 'hometax'
        req_dict['svcCd'] = 'Z1001'
        req_dict['loginMethod'] = 'CERT'

        certId = request.POST['certId']
        print(certId)
        agentId = request.POST['agentId']
        print(agentId)
        userId = request.POST['userId']

        cert_info_obj = CtaCert.objects.get(pk=certId)
        signCert = cert_info_obj.file1
        signPri = cert_info_obj.file2
        signPw = cert_info_obj.cert_pw

        ctaidpw_obj = CtaIdPw.objects.get(pk=agentId)
        agentPw = ctaidpw_obj.pw

        bsidpw_obj = BsIdPw.objects.get(pk=userId)
        userPw = bsidpw_obj.pw

        req_dict['agentId'] = agentId
        req_dict['userId'] = userId
        req_dict['signCert'] = signCert
        req_dict['signPri'] = signPri
        req_dict['signPw'] = signPw
        req_dict['agentPw'] = agentPw
        req_dict['userPw'] = userPw

        req_str = json.dumps(req_dict, ensure_ascii=False)
        print(type(req_str))
        print(req_str)
        res_dict = ift_call2(req_str)
        # res_str, req_str = iftServicedll.serviceCall2(req_str)
        # print(res_str)
        # res_dic = json.loads(res_str)
        
        # return redirect("/nts/")
        return JsonResponse(res_dict)

        


        

nts/templates/nts/bsid_list_options.html
{% comment %} <option value="">---------</option> {% endcomment %}
{% for bsid in bsidpws %}
<option value="{{ bsid.pk }}" >{{ bsid.bsid }}</option>
{% endfor %}

nts/templates/nts/ctaid_list_options.html
{% comment %} <option value="">---------</option> {% endcomment %}
{% for ctaid in ctaidpws %}
<option value="{{ ctaid.pk }}" >{{ ctaid.ctaid }}</option>
{% endfor %}

nts/templates/nts/nts_home.html
{% extends 'base.html' %}
{% block title %}<title>HomeTax</title>
{% endblock title %}

{% block nav_left %}
{% endblock nav_left %}

{% block content %}
<p><h5><mark> 홈택스 로그인 정보 저장</mark></h5></p><hr>

<div class="form-row">
    {% comment %} <form action="{% url 'nts:nts_Z1001' %}" method="post">
    {% csrf_token %} {% endcomment %}
    <div class="form-group input-group-sm">
        <button id="show" class="form-control btn btn-primary btn-sm" onclick="location.href='{% url 'nts:getcert' %}'">인증서등록</button>
    </div>
    <div class="form-group input-group-sm">
        <label for="ctacert"><b>&nbsp&nbsp인증서&nbsp</b></label>
    </div>
    <div class="form-group input-group-sm">
        <select name="certId" id="id_ctacert">
            {% if ctacert_obj %}
                {% for ctacert in ctacert_obj %}
                    <option value="{{ctacert.id}}" {% if ctacert.num_used.max %} selected="selected" {% endif %}>{{ctacert.cert_nm}}</option>
                {% endfor %}
            {% else %}
                <option>등록요망</option>   
            {% endif %}
        </select>
    </div>
    <div class="form-group col-md-1 input-group-sm">
        <button type="submit" class="btn btn-danger btn-sm" onclick="delete_cert()">삭제</button>
    </div>
    <div class="form-group col-md-1 input-group-sm">
        {% if ctaidpw_obj %}
            <select name="ctaId" id="id_ctaidpw" >
            {% comment %} {% for cta in ctaidpw_obj %}
                <option value="{{ cta.ctaid }}">{{ cta.ctaid }}</option>
            {% endfor %} {% endcomment %}
            </select>
        {% endif %}
    </div>
    <div class="form-group col-md-1 input-group-sm">
        {% if bsidpw_obj %}
            <select name="bsId" id="id_bsidpw">
                {% comment %} {% for bs in bsidpw_obj %}
                    <option value="{{ bs.bsid }}">{{ bs.bsid }}</option>
                {% endfor %} {% endcomment %}
            </select>
        {% endif %}
    </div>
    <div class="form-group col-md-1 input-group-sm">
        <button type="submit" class="btn btn-success btn-sm" id="btn_ask" onclick="" >조회</button>
    </div>
    {% comment %} </form> {% endcomment %}
</div>
{% if messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert" >
    <strong> 
        {% for message in messages %}
        {{ message.tags }}
        {{ message.message }}
        {% endfor %}
    </strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button> 
</div>
{% endif %}

<div class="form-row">
    <div class="form-row col-auto">
        <div class="form-group input-group-sm">
            <label for="agentId"><b>세무대리인&nbsp&nbsp</b></label>
        </div>
        <div class="form-group input-group-sm">
            <input type="text" class="form-control" id="agentId" placeholder="CTA ID" value="">
        </div>
        <div class="form-group input-group-sm">
            <input type="password" class="form-control" id="agentPw" placeholder="PassWord">
        </div>
        <div class="form-group input-group-sm">
            <label for="ctaPwTogle">
                <input type="checkbox" class="form-check-input" id="ctaPwTogle">
            </label>
        </div>
    </div>
    <div class="form-row col-auto">
        <div class="form-group input-group-sm">
            <label for="userId"><b>&nbsp&nbsp부서사용자&nbsp&nbsp</b></label>
        </div>
        <div class="form-group input-group-sm">
            <input type="text" class="form-control" id="userId" placeholder="사용자 ID">
        </div>
        <div class="form-group input-group-sm">
            <input type="password" class="form-control" id="userPw" placeholder="PassWord">
        </div>
        <div class="form-group input-group-sm">
            <label for="userPwTogle">
                <input type="checkbox" class="form-check-input" id="userPwTogle">
            </label>
        </div>
    </div>
    <div class="form-group col-md-1 input-group-sm">
        <button id="btn_cta_bs_idpw" class="form-control btn btn-primary btn-sm">저장</button>
    </div>  
</div>
<hr>
{% endblock content %}

{% block javascript %}
<script>

function get_selected_cert(){
    var cert_id = $("#id_ctacert option:selected").val();
    if(cert_id !="등록요망"){
        return cert_id
    } else {
        return false
    };    
};

function delete_cert(){
    var cert_id = get_selected_cert();
    if(cert_id != false){
        $.ajax({                    // Ajax 메소드 http://bitly.kr/RICE9SXo
            url: "{% url 'nts:cert-delete' %}",
            type: "POST",
            data:{'id':cert_id, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            datatype:"json",
            success: function(response){
            alert( response.object  + "가 삭제되었습니다.");
            },
        })
        .always(function(){
            window.location.reload();       // 새로고침
        });
    }; 
};

$( "#show" ).click(function() {
    $( "div.alert" ).show("slow");
});

//<!-- 인포텍 인증서 모듈 메세지 -->

$(function(){
    {% if messages %}
        {% for message in messages %}
            var msg = "{{ message.message }}";            
        {% endfor %}
        <!-- alert(msg);         -->
    {% endif %}
    var id_cert = $("#id_ctacert option:selected").val();
    $.ajax({
        url: "{% url 'nts:set_ctaid' %}",
        type: "GET",
        data: {
            'id_cert': id_cert
        },
        success: function(data){
            $("#id_ctaidpw").html(data);
        }
    })
    .done(function(){
        var id_ctaid = $("#id_ctaidpw option:selected").val();
        $.ajax({
            url: "{% url 'nts:set_bsid' %}",
            type: "GET",
            data: {
                'id_cert': id_cert,
                'id_ctaid': id_ctaid
            },
            success: function(data){
                $("#id_bsidpw").html(data);
            }
        });
    });   
});

$("#id_ctacert").on("click change", function(){
    var id_cert = $("#id_ctacert option:selected").val();
    $.ajax({
        url: "{% url 'nts:set_ctaid' %}",
        type: "GET",
        data: {
            'id_cert': id_cert
        },
        success: function(data){
            $("#id_ctaidpw").html(data);
        }
    })
    .done(function(){
        var id_ctaid = $("#id_ctaidpw option:selected").val();
        $.ajax({
            url: "{% url 'nts:set_bsid' %}",
            type: "GET",
            data: {
                'id_cert': id_cert,
                'id_ctaid': id_ctaid
            },
            success: function(data){
                $("#id_bsidpw").html(data);
                $("#agentId").val(id_ctaid);
                get_ctapw();
                var userId = $("#id_bsidpw option:selected").val();
                $("#userId").val(userId);
                get_bspw();
            }
        });
    });   
}); 

function get_ctapw(){
    var id_ctaid = $("#id_ctaidpw option:selected").val();
    $.ajax({
        url: "{% url 'nts:get_ctaidpw' %}",
        type: "GET",
        data: {
            'id_ctaid': id_ctaid
        },
        datatype: "json",
        success: function(data){
            jp = JSON.parse(data)
            var ctapw = jp[0].fields.pw;
            $("#agentPw").val(ctapw);
        }
    });
};

function get_bspw(){
    var userId = $("#id_bsidpw option:selected").val();
    $.ajax({
        url: "{% url 'nts:get_bsidpw' %}",
        type: "GET",
        data: {
            'userId': userId
        },
        datatype: "json",
        success: function(data){
            jp = JSON.parse(data)
            var userPw = jp[0].fields.pw;
            $("#userPw").val(userPw);
        }
    });
};

// jquery multi event
$("#id_ctaidpw").on("click change", function(){
    var id_cert = $("#id_ctacert option:selected").val();
    var id_ctaid = $("#id_ctaidpw option:selected").val();
    $.ajax({
        url: "{% url 'nts:set_bsid' %}",
        type: "GET",
        data: {
            'id_cert': id_cert,
            'id_ctaid': id_ctaid
        },
        success: function(data){
            $("#id_bsidpw").html(data);
        }
    })
    .done(function(){
        var id_ctaid = $("#id_ctaidpw option:selected").val();
        $.ajax({
            url: "{% url 'nts:set_bsid' %}",
            type: "GET",
            data: {
                'id_cert': id_cert,
                'id_ctaid': id_ctaid
            },
            success: function(data){
                $("#id_bsidpw").html(data);
                $("#agentId").val(id_ctaid);
                get_ctapw();
                var userId = $("#id_bsidpw option:selected").val();
                $("#userId").val(userId);
                get_bspw();
            }
        });
    });
}); 

$('#btn_cta_bs_idpw').click(function(){
    var certId = get_selected_cert();
    var agentId = $('#agentId').val();
    var agentPw = $('#agentPw').val();
    var userId = $('#userId').val();
    var userPw = $('#userPw').val();
    //alert(cert_nm + agentId + "_" + userId + "_")
    $.ajax({
        url:"{% url 'nts:get_idpw' %}",
        type: 'POST',
        data: {
            'certId': certId,
            'agentId':agentId,
            'agentPw':agentPw,
            'userId':userId,
            'userPw':userPw,
            'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        datatype:'json',
        success:function(res){
            alert(res.res_cta_idpw.ctaid);
        },
        error:function(request, status, error){
            alert("실패");
            alert(request);
            alert(status);
            alert(error);
        },
    })
    .always(function(){
        window.location.reload();       // 새로고침
    });
});

// 패스워드 보이기 체크박스 https://www.tutorialrepublic.com/faq/how-to-check-a-checkbox-is-checked-or-not-using-jquery.php
$("#ctaPwTogle").click(function(){
    if($(this).is(":checked")){
        $("#agentPw").prop("type", "text");
    }
    else if($(this).is(":not(:checked)")){
        $("#agentPw").prop("type", "password");
    }
});
$("#userPwTogle").click(function(){
    if($(this).is(":checked")){
        $("#userPw").prop("type", "text");
    }
    else if($(this).is(":not(:checked)")){
        $("#userPw").prop("type", "password");
    }
});

$("#btn_ask").click(function(){
    var certId = $("#id_ctacert option:selected").val();
    var agentId = $("#id_ctaidpw option:selected").val();
    var userId = $("#id_bsidpw option:selected").val();
    console.log("certId: " + certId);
    console.log("agentId: " + agentId);
    console.log("userId: " + userId);
    $.ajax({
        url: "{% url 'nts:nts_Z1001' %}",
        type: 'POST',
        data:{
           'certId': certId, 
           'agentId': agentId, 
           'userId': userId,
           'csrfmiddlewaretoken': '{{ csrf_token }}' 
        },
        datatype: 'json',
        async: false
    })
    .done(function(data){
        console.log(data);
    });
});

{% comment %} 
$("#btn_ask").click(function(){
    var certId = $("#id_ctacert option:selected").val();
    var agentId = $("#id_ctaidpw option:selected").val();
    var userId = $("#id_bsidpw option:selected").val();
    console.log("certId: " + certId);
    console.log("agentId: " + agentId);
    console.log("userId: " + userId);
    $.ajax({
        url: "{% url 'nts:nts_Z1001' %}",
        type: 'POST',
        data:{
           'certId': certId, 
           'agentId': agentId, 
           'userId': userId,
           'csrfmiddlewaretoken': '{{ csrf_token }}' 
        },
        datatype: 'json',
        async: false,
        success: function(res){
            alert(res);
        }
    })
}); {% endcomment %}

// data.json : {name: "Jhon", age: 29}

</script>
{% endblock javascript %}